
IFPLUGD_SYSTEMD_SERVICE_VERSION = 0.0.1
IFPLUGD_SYSTEMD_SERVICE_LICENSE = MIT
IFPLUGD_SYSTEMD_SERVICE_SOURCE =
IFPLUGD_SYSTEMD_SERVICE_SITE =

define IFPLUGD_SYSTEMD_SERVICE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 644 $(IFPLUGD_SYSTEMD_SERVICE_PKGDIR)/src/ifplugd@.service $(TARGET_DIR)/usr/lib/systemd/system/ifplugd@.service
endef

$(eval $(generic-package))
