
UHTTPD_SYSTEMD_SERVICE_VERSION = 1.1.1
UHTTPD_SYSTEMD_SERVICE_LICENSE = MIT
UHTTPD_SYSTEMD_SERVICE_SOURCE =
UHTTPD_SYSTEMD_SERVICE_SITE =

define UHTTPD_SYSTEMD_SERVICE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 644 $(UHTTPD_SYSTEMD_SERVICE_PKGDIR)/src/uhttpd.service $(TARGET_DIR)/usr/lib/systemd/system/uhttpd.service
endef

$(eval $(generic-package))
